### ISSUE TITLE
Error for OSX in 2.6: uninitialized constant AFMotion::SessionClientDSL::UIDevice

### ISSUE THREAD

**Issue by superplussed** [clayallsopp/afmotion#105]
I get the following error when using AFmotion after upgrading to 2.6:

2015-12-14 09:25:51.540 Seedlng Producer[10610:230781] *** Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant AFMotion::SessionClientDSL::UIDevice (NameError)

Downgrading to 2.5 removes the error.

I see in the code that there is only one reference to UIDevice in session_client.rb, but I'm a bit of a noob to Rubymotion and I'm not sure what to change that line to so that it is fixed.

**Comment by tsugua** [comment]
I'm seeing the same thing on OSX. Looks like an iOS library was left in for the OSX build. UIDevice isn't available on OSX.

**Comment by tsugua** [comment]
Perhaps in line 94? 
`      background: (UIDevice.currentDevice.systemVersion.to_f >= 8.0 ? "backgroundSessionConfigurationWithIdentifier:" : "backgroundSessionConfiguration:").to_sym
`

**Comment by tsugua** [comment]
https://github.com/clayallsopp/afmotion/commit/e3d5031ff4dbaf1ddbee067a96148831620ad84a
