### ISSUE TITLE
Synchronous operation

### ISSUE THREAD

**Issue by hgani** [clayallsopp/afmotion#110]
Hi,

Is there any way to make the network operation synchronous (block until we get response)?

The reason why this is important is we are trying to use Amazon Cognito, as described in http://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

- (AWSTask *)refresh {
    `// Call to your backend`

    self.identityId = response.identityId;
    self.token = response.token;
    return [AWSTask taskWithResult:self.identityId];
}

The "Call to you backend" bit has to be synchronous so that we can get the value of "identityId" and "token".

Thanks

**Comment by sajoku** [comment]
@hgani I believe there isn't an option to perform synchronous requests. 

I "fixed" this by adding a hud when performing the request, making sure the user is not able to do any other actions but must wait for the request to finish. 

This is sort of how that looks in my code.

Web.rb (class with post/put/get/delete templates
```ruby
def self.get(url, data=nil, &blk)
    show_hud
    self.client.get(url, data) do |response|
      hide_hud
      #handle response here
    end
  end

  def self.hide_hud
    MBProgressHUD.hideHUDForView(App.shared.keyWindow, animated: true)
  end

  def self.show_hud
    hud = MBProgressHUD.showHUDAddedTo(App.shared.keyWindow, animated: true)
    hud.labelText = "Loading"
  end
```
Get the invitations for example.
``` ruby
def self.get_invitations(&blk)
    Web::get("user/invitations.json") do |response|
      blk.call(response)
    end
  end
```

You do need to add  'MBProgressHUD' as a pod in your Makefile.

**Comment by markrickert** [comment]
@sajoku Is correct. You should never run networking operations synchronously. You should block the UI while the network request is running if you don't want the user to interact with anything.

I'd recommend `Motion::Blitz` for this. It has a great DSL and is easy to implement in your project: https://github.com/dblandin/motion-blitz
