### ISSUE TITLE
How to get JSON object during error?

### ISSUE THREAD

**Issue by kapso** [clayallsopp/afmotion#59]
On the server I am sending a json error (not 200 OK) object from my rails app, say something like this - 

``` ruby
render json: { errors: ["User not found"] }, status: :not_found
```

JSON response:

``` javascript
{
  "errors": ["User not found"]
}
```

Inside my iOS app, how do I get access to error object on - `failure?` since `result.object` does not return error JSON object, its returns `nil`

``` ruby
http_client(:host_url).post(URL_AUTH_SIGNIN, auth: data) do |result|
  @response = result.object

  if result.success?
    handle_login_success(@response)
  else
    # @response in nil here??
    handle_server_error(@response)
  end
end

def http_client(type = :api_url)
  url = type == :api_url ? URL_BASE : URL_HOST

  AFMotion::SessionClient.build(url) do
    session_configuration :default
    all_headers.each { |key, value| header(key, value) }
    response_serializer :json
  end
end
```

**Comment by nerakdon** [comment]
To get this working for me, I had to:

1. Put both the .h and the .m files in the directory `vendor/JSONResponseSerializerWithData`
1. Reference that in my `Rakefile` with the following: `app.vendor_project('vendor/JSONResponseSerializerWithData', :static)`
1. Fix a typo in the `JSONResponseSerializerWithData.m` file (it was missing a `@end` at the end). 

None of those were obvious based on my mostly-ruby background, so I thought someone else might have the same problem.
