### ISSUE TITLE
iOS 8 ** BUILD FAILED **

### ISSUE THREAD

**Issue by chrishale** [clayallsopp/afmotion#72]
I've got a pretty much empty rubymotion (2.33) project, with Xcode 6.0.1. When I add 'afmotion' to my Gemfile, bundle and rake pod:install. Then rake. I get this;

    Build ./build/iPhoneSimulator-8.0-Development
    2014-09-18 12:48:46.081 xcodebuild[5701:1007] [MT] PluginLoading: Required plug-in compatibility UUID C4A681B0-4A26-480E-93EC-1218098B9AA0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    Build ./vendor/Pods/Pods.xcodeproj [AFNetworking - Release]
    Compile ./vendor/Pods/Pods-AFNetworking-prefix.pch
    Compile ./vendor/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
    Compile ./vendor/Pods/AFNetworking/AFNetworking/AFHTTPRequestOperationManager.m
    Compile ./vendor/Pods/AFNetworking/AFNetworking/AFNetworkReachabilityManager.m
    Compile ./vendor/Pods/AFNetworking/AFNetworking/AFHTTPSessionManager.m
    Compile ./vendor/Pods/AFNetworking/AFNetworking/AFSecurityPolicy.m
    Compile ./vendor/Pods/AFNetworking/AFNetworking/AFHTTPRequestOperation.m
    Compile ./vendor/Pods/AFNetworking/AFNetworking/AFURLConnectionOperation.m
    Compile ./vendor/Pods/AFNetworking/AFNetworking/AFURLRequestSerialization.m
    ** BUILD FAILED **

    The following build commands failed:
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFNetworkActivityIndicatorManager.o AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFHTTPRequestOperationManager.o AFNetworking/AFNetworking/AFHTTPRequestOperationManager.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFNetworkReachabilityManager.o AFNetworking/AFNetworking/AFNetworkReachabilityManager.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFHTTPSessionManager.o AFNetworking/AFNetworking/AFHTTPSessionManager.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFSecurityPolicy.o AFNetworking/AFNetworking/AFSecurityPolicy.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFHTTPRequestOperation.o AFNetworking/AFNetworking/AFHTTPRequestOperation.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFURLConnectionOperation.o AFNetworking/AFNetworking/AFURLConnectionOperation.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/Pods.build/Release-iphonesimulator/Pods-AFNetworking.build/Objects-normal/i386/AFURLRequestSerialization.o AFNetworking/AFNetworking/AFURLRequestSerialization.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (8 failures)
    ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.

Anybody got any ideas?

**Comment by markrickert** [comment]
Looks like we should be able to close this issue, no?
