### ISSUE TITLE
AFJSONRequestSerializer issue prevents app from loading

### ISSUE THREAD

**Issue by dam13n** [clayallsopp/afmotion#79]
**\* Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant AFMotion::ClientDSL::AFJSONRequestSerializer (NameError)

I was playing around with a few gems. I ran a pod:install somewhere in there. Eventually I got this. I reverted back to a working version but am still getting this error now.

**Comment by brandoncc** [comment]
Thank you @dam13n, this fixed it for me too.
