### ISSUE TITLE
Get Headers for JSON response

### ISSUE THREAD

**Issue by cbetta** [clayallsopp/afmotion#86]
How do I get the response headers when using `response_serializer :json`?

**Comment by clayallsopp** [comment]
for an individual request?

the `result` object will have either an `operation` or `task` field

if `operation` - `result.operation.response.allHeaderFields`

if `task` - `result.task.reponse.allHeaderFields`

**Comment by cbetta** [comment]
Thanks, that really helped

**Comment by uksa** [comment]
This was also really useful to me, it would be really helpful to put into the read-me - happy to oblige??

**Comment by clayallsopp** [comment]
@uksa I'm happy to merge any PRs for the README :)

**Comment by augustosamame** [comment]
Hi. Sorry for the newbie question. I don't have a result object:
undefined local variable or method `result' for Motion::Authentication::DeviseTokenAuthGem:Class (NameError)

There is a valid response object though. How do I get the headers from it then? (the access token is sent back as a header field from my API)

**Comment by augustosamame** [comment]
Never mind. Figured it out. response or result is merely the name you assign to your response object. In my case it is response, so response.operation.response.allHeaderFields returned the response headers I needed.
