### ISSUE TITLE
No response on HTTP.get

### ISSUE THREAD

**Issue by andreheijstek** [clayallsopp/afmotion#94]
I get no response at all on this code
   AFMotion::HTTP.get("http://google.com") do |result|
      p result.body
    end

The funny thing is that, in parallel, I get this working on a small test app directly copied from Clay's RubyMotion book. I had to tweak it a bit, as the book is still fully using BubbleWrap.
But on my real app, I get no response at all.
As far as I can see almost everything is the same, except for using some more Gems: 'ProMotion', 'motion-kit',  'sugarcube'.
After Rake I get the following message:
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
      minitest (~> 5.1)

I've got these before in the book app, but after update Gems and Bundle, that disappeared. But I can't get these message to disappear in my real app.

Any suggestions?

**Comment by clayallsopp** [comment]
No idea - if you can reproduce it with a small gist or repro, then it can probably be debugged

**Comment by andreheijstek** [comment]
That would be awesome!
I’ve uploaded the project to: https://github.com/andreheijstek/SintJansGemeenteApp <https://github.com/andreheijstek/SintJansGemeenteApp>

Regards, André

**Comment by andreheijstek** [comment]
Hi Clay,

I’ve kind of got it to working right now.
I called the method that did the HTTP request so far only from an rspec test (trying to behave nicely as a TDD developer). But for whatever reason it does not work in that way.
Just now, I called the method directly, and now it works.

Any idea why it does not work from rspec?

Regards, André

**Comment by clayallsopp** [comment]
Hm, no idea about that, but I'm glad it's working as intended in non-testing mode
