### ISSUE TITLE
Any way of getting progress of GET operations?

### ISSUE THREAD

**Issue by markrickert** [clayallsopp/afmotion#95]
I know it's possible with multipart POSTs, but is there any way to get progress of GET operations?

**Comment by clayallsopp** [comment]
It looks like you have to do some KVO magic: http://stackoverflow.com/a/19380812

but nothing supported directly in the AFMotion API

**Comment by markrickert** [comment]
I added it to a fork of AFMotion. Is a feature like this something you'd be interested in merging?

It's very ready for a pr, but it was a simple addition to the library... However I'm abusing the params parameter :D

https://github.com/clayallsopp/afmotion/compare/master...markrickert:progress_block

**Comment by clayallsopp** [comment]
Sounds good to me - just add a note to the README, and preferably a test

**Comment by markrickert** [comment]
Oh yeah... i'd definitely add tests... Just wanted to make sure you're ok with me bastardizing the http request params variable to send in a block :)
