### ISSUE TITLE
Crash with AFNetworking 2.6.0

### ISSUE THREAD

**Issue by MarkVillacampa** [clayallsopp/afmotion#99]
The latest version of AFNetworking (2.6.0) causes a crash on the current version of RubyMotion (3.14).

```
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
Objective-C stub for message `GET:parameters:success:failure:' type `@@:@@@?@?' not precompiled. Make sure you properly link with the framework or library that defines this message.
```

The next version of RubyMotion fixes this issue, but if someone has updated to AFNetworking by error, you can force using version 2.5.X by adding the following to your Rakefile:

```ruby
app.pods do
  pod 'AFNetworking', '~> 2.5.0'
end
```

If any afmotion maintainer considers this is worth releasing a new version, the only fix needed is adding the trailing zero in this line:

https://github.com/clayallsopp/afmotion/blob/master/lib/afmotion.rb#L19

**Comment by markrickert** [comment]
Heh. I was just going to report this... `'~> 2.5'` will lock to anything below `3.0`. Should be changed to `'~> 2.5.0'`

**Comment by clayallsopp** [comment]
Can someone submit a PR? Happy to merge and then update the gem
